name: Build & Push Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OWNER: jeff-app-com
  IMAGE_NAME: base-spring-docker-image
  IMAGE_NAME_11: base-spring-docker-image-11-slim
  IMAGE_NAME_17: base-spring-docker-image-17-slim

jobs:
  build-and-push:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v2-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v2-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jeff-machine-user
          password: ${{ secrets.CR_PAT }}
      - name: Build and push v11
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            JDK_TAG=11-slim
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME_11 }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and push v17
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            JDK_TAG=17-slim
          tags: ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME_17 }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      # This ugly bit is necessary if you don't want your cache to grow forever till it hits GitHub's limit of 5GB.
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
