name: Build & Push Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OWNER: jeff-app-com
  IMAGE_NAME: base-spring-docker-image

jobs:
  build-and-push:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build
        run: docker build -t ghcr.io/$OWNER/$IMAGE_NAME:latest .
      - name: Push
        run: docker push ghcr.io/$OWNER/$IMAGE_NAME:latest
