name: Build & Push Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: jeff/base-spring-docker-image

jobs:
  build-and-push:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login in Container Registry
        run: |
          export CR_PAT=${{ secrets.CR_PAT }} \
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
      - name: Build
        run: |
          docker build -t $IMAGE_NAME .
